#!/usr/bin/env python3
"""Honeyfiles: files that exist only to be touched by someone who shouldn't.

This is detection, not protection. It cannot stop a breach and nothing here
should be mistaken for a lock on the door - by the time an attacker reads these
they are already inside. What it does is tell you *immediately*, which is the
difference between finding out now and finding out in six months.

The signal is clean only as long as nothing sweeps these files up in bulk, and
that is a placement problem, not a theory. On 2026-09-26 two honeyfiles living
in thunder-data/ fired at 03:12 because a routine `grep -rli ... --include='*.json'
--include='*.txt'` over /home/blayne read all 205 files in the source tree. No
intruder, six CRITICAL alerts, and an hour spent proving it was nothing.

So: keep honeyfiles OUT of any tree that gets searched, and give them
extensions a code search will not ask for. The three that have never
false-positived are .csv and an extension-less key, which every
`--include='*.py' --include='*.json'` style grep skips for free. That is the
whole trick, and it is worth more than the bait name.

What this still cannot tell you is WHO read the file - inotify reports the
path and the event, never the pid. Attributing an access needs auditd or
fanotify. Until then, one access is one alert, and triage means going to the
journal and the process tree to find out what was running.

Names are chosen to be the first thing someone would reach for. Contents are
whatever you like - they are never read by anything real.
"""
import json
import os
import subprocess
import sys
import time
from datetime import datetime, timezone
from pathlib import Path

DATA = Path(os.environ.get("THUNDER_DATA", "/home/blayne/Thunder-chat/Thunder-chat-v3/thunder-main-api/thunder-data"))
ALERTS = DATA / "canary_alerts.log"
STATE = DATA / "canary_state.json"

# Where a snooper would actually look, and what they would want. Two rules,
# both learned the hard way: never inside a source tree, and never an
# extension a code search includes (.py .json .txt .md .kt .js .service ...).
# A snooper opens a file because of its name; a grep opens it because of its
# suffix. Pick names for the first and suffixes that dodge the second.
HONEYFILES = {
    Path.home() / "patients_2026_backup.csv": "csv",
    Path.home() / "billing_export_Q3.csv": "csv",
    Path.home() / ".ssh" / "id_rsa_backup": "key",
    Path.home() / "patient_records_export.csv": "csv",
    Path.home() / "credentials_backup.bak": "creds",
}

FILLER = """If you are reading this file, you are somewhere you should not be.
Nothing here is real. This file exists to tell the owner that you opened it,
and it already has. Every access is logged with a timestamp.

""" + ("penis " * 200 + "\n") * 40


def body(kind: str) -> str:
    """Plausible-looking headers so it survives a glance, then filler."""
    if kind == "csv":
        head = ("patient_id,last_name,first_name,dob,ssn,insurer,claim_no,balance\n"
                "# export generated by billing system - DO NOT DISTRIBUTE\n")
    elif kind == "json":
        head = '{"_comment": "full patient export", "records": [\n'
    elif kind == "key":
        head = "-----BEGIN OPENSSH PRIVATE KEY-----\n"
    else:
        head = "# service credentials - production\n"
    return head + FILLER


def plant() -> list[Path]:
    made = []
    for path, kind in HONEYFILES.items():
        try:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(body(kind))
            path.chmod(0o600)
            made.append(path)
        except Exception as e:
            print(f"  could not plant {path}: {e}", file=sys.stderr)
    STATE.write_text(json.dumps(
        {"planted": [str(p) for p in made], "at": int(time.time())}, indent=2))
    return made


def alert(path: str, event: str) -> None:
    rec = {
        "at": datetime.now(timezone.utc).isoformat(),
        "file": path,
        "event": event,
        "severity": "CRITICAL",
        "meaning": "a honeyfile was accessed - nothing legitimate reads these",
    }
    with ALERTS.open("a") as f:
        f.write(json.dumps(rec) + "\n")
    # Also to the system journal, so it lands wherever logs are already watched.
    subprocess.run(["logger", "-p", "auth.crit", "-t", "thunder-canary",
                    f"HONEYFILE ACCESSED: {path} ({event})"], check=False)
    print(f"!! {rec['at']}  {path}  {event}", flush=True)


def watch(paths: list[Path]) -> None:
    if not paths:
        print("nothing planted, nothing to watch", file=sys.stderr)
        return
    print(f"watching {len(paths)} honeyfiles", flush=True)
    # open covers reading it; access covers most tooling; attrib catches a
    # chmod/stat sweep, which is often what a script does before reading.
    proc = subprocess.Popen(
        ["inotifywait", "-m", "-q", "--format", "%w|%e",
         "-e", "open", "-e", "access", "-e", "attrib", *map(str, paths)],
        stdout=subprocess.PIPE, text=True,
    )
    for line in proc.stdout:
        path, _, event = line.strip().partition("|")
        if path:
            alert(path, event)


if __name__ == "__main__":
    if len(sys.argv) > 1 and sys.argv[1] == "plant":
        made = plant()
        print(f"planted {len(made)}:")
        for p in made:
            print("  ", p)
    else:
        planted = [Path(p) for p in
                   json.loads(STATE.read_text())["planted"]] if STATE.exists() else plant()
        watch([p for p in planted if p.exists()])
