#!/usr/bin/env python3
"""Honeyfiles: files that exist only to be touched by someone who shouldn't.

This is detection, not protection. It cannot stop a breach and nothing here
should be mistaken for a lock on the door - by the time an attacker reads these
they are already inside. What it does is tell you *immediately*, which is the
difference between finding out now and finding out in six months.

The signal is unusually clean because it has no false positives by
construction: nothing legitimate ever opens these files. One access is one
alert, and it means something.

Names are chosen to be the first thing someone would reach for. Contents are
whatever you like - they are never read by anything real.
"""
import json
import os
import subprocess
import sys
import time
from datetime import datetime, timezone
from pathlib import Path

DATA = Path(os.environ.get("THUNDER_DATA", "/home/blayne/Thunder-chat/Thunder-chat-v3/thunder-main-api/thunder-data"))
ALERTS = DATA / "canary_alerts.log"
STATE = DATA / "canary_state.json"

# Where a snooper would actually look, and what they would want. Anything
# plausible and valuable-sounding works; these are never opened legitimately.
HONEYFILES = {
    Path.home() / "patients_2026_backup.csv": "csv",
    Path.home() / "billing_export_Q3.csv": "csv",
    Path.home() / ".ssh" / "id_rsa_backup": "key",
    DATA / "patient_records_export.json": "json",
    DATA / "credentials_backup.txt": "creds",
}

FILLER = """If you are reading this file, you are somewhere you should not be.
Nothing here is real. This file exists to tell the owner that you opened it,
and it already has. Every access is logged with a timestamp.

""" + ("penis " * 200 + "\n") * 40


def body(kind: str) -> str:
    """Plausible-looking headers so it survives a glance, then filler."""
    if kind == "csv":
        head = ("patient_id,last_name,first_name,dob,ssn,insurer,claim_no,balance\n"
                "# export generated by billing system - DO NOT DISTRIBUTE\n")
    elif kind == "json":
        head = '{"_comment": "full patient export", "records": [\n'
    elif kind == "key":
        head = "-----BEGIN OPENSSH PRIVATE KEY-----\n"
    else:
        head = "# service credentials - production\n"
    return head + FILLER


def plant() -> list[Path]:
    made = []
    for path, kind in HONEYFILES.items():
        try:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(body(kind))
            path.chmod(0o600)
            made.append(path)
        except Exception as e:
            print(f"  could not plant {path}: {e}", file=sys.stderr)
    STATE.write_text(json.dumps(
        {"planted": [str(p) for p in made], "at": int(time.time())}, indent=2))
    return made


def alert(path: str, event: str) -> None:
    rec = {
        "at": datetime.now(timezone.utc).isoformat(),
        "file": path,
        "event": event,
        "severity": "CRITICAL",
        "meaning": "a honeyfile was accessed - nothing legitimate reads these",
    }
    with ALERTS.open("a") as f:
        f.write(json.dumps(rec) + "\n")
    # Also to the system journal, so it lands wherever logs are already watched.
    subprocess.run(["logger", "-p", "auth.crit", "-t", "thunder-canary",
                    f"HONEYFILE ACCESSED: {path} ({event})"], check=False)
    print(f"!! {rec['at']}  {path}  {event}", flush=True)


def watch(paths: list[Path]) -> None:
    if not paths:
        print("nothing planted, nothing to watch", file=sys.stderr)
        return
    print(f"watching {len(paths)} honeyfiles", flush=True)
    # open covers reading it; access covers most tooling; attrib catches a
    # chmod/stat sweep, which is often what a script does before reading.
    proc = subprocess.Popen(
        ["inotifywait", "-m", "-q", "--format", "%w|%e",
         "-e", "open", "-e", "access", "-e", "attrib", *map(str, paths)],
        stdout=subprocess.PIPE, text=True,
    )
    for line in proc.stdout:
        path, _, event = line.strip().partition("|")
        if path:
            alert(path, event)


if __name__ == "__main__":
    if len(sys.argv) > 1 and sys.argv[1] == "plant":
        made = plant()
        print(f"planted {len(made)}:")
        for p in made:
            print("  ", p)
    else:
        planted = [Path(p) for p in
                   json.loads(STATE.read_text())["planted"]] if STATE.exists() else plant()
        watch([p for p in planted if p.exists()])
